---
title: "Evaluating asymptotic intervals of FH estimates with and without variance smoothing, using simulated data mirroring Kenya height-for-age"
author: "Alana McGovern"
date: "`r Sys.Date()`"
output: pdf_document
---

The goal of this simulation study is to evaluate how well variance smoothing can improve interval properties under the FH model. We simulate data meant to mirror the height-for-age z-score in the 2022 Kenya DHS.

# Simulation Design

1. Obtain weighted stratified mean estimates $(\boldsymbol{\mu_R},\boldsymbol{\mu_U})$, at the admin2 level, using the DHS data (height-for-age)

2. Generate a continuous response, for each sampled individual $k$ in cluster $c$, in strata $h$, in admin 2 area $j$, in admin 1  area $i$, from either

a. no cluster effect: 
  $$y_{ijhck}^{(s)} \sim \mathcal{N}(\mu_{jh}, \sigma_{jh}^{2(s)})$$
  
b. cluster effect: 
  $$y_{ijhck}^{(s)} \sim \mathcal{N}(\mu_{jh}+\epsilon_c^{(s)}, \sigma_{jh}^{2(s)})$$

where $\sigma_{jh}^{2(s)}$ is generated from,
  $$log(\sigma_{jR}^{2(s)}) = \alpha + Z\gamma + v_j$$ 
  $$\sigma_{jU}^{2(s)}=(1+\kappa_{i[j]})\sigma_{jR}^{2(s)}$$ where $Z$ is a covariate matrix, and $v$ can be distributed either IID or BYM2.
  
3. Take a two-stage stratified sample, with sampling design and sizes chosen to mirror the Kenya 2022 DHS.
  
4. Fit models (admin1 and admin2 level) using a mean model with BYM2 effects and covariates and the following variance models:

a. IID variance and constant strata effect: 
    $$log(\sigma_{iR}^{2(s)})\sim\mathcal{N}(\alpha,1/\tau)$$
  $$\sigma_{iU}^{2(s)}=(1+\kappa)\sigma_{iR}^{2(s)}$$
b. Structured variance and constant strata effect: 
  $$log(\sigma_{iR}^{2(s)}) = \alpha + Z\gamma + v_i$$ 
  $$\sigma_{iU}^{2(s)}=(1+\kappa)\sigma_{iR}^{2(s)}$$ where $Z$ is a covariate matrix, and $v$ can be distributed either IID or BYM2
  
c. IID variance and varied strata effect:
 $$log(\sigma_{iR}^{2(s)})\sim\mathcal{N}(\alpha,1/\tau)$$
  $$\sigma_{iU}^{2(s)}=(1+\kappa_i)\sigma_{iR}^{2(s)}$$  
  where $\kappa_i$ is always an admin1 level parameter, regardless of model level
  
d. Structured variance and varied strata effect:
 $$log(\sigma_{iR}^{2(s)}) = \alpha + Z\gamma + v_i$$ 
  $$\sigma_{iU}^{2(s)}=(1+\kappa_i)\sigma_{iR}^{2(s)}$$
  

5. Compare each model to the oracle model (where sampling variance estimate is correct), standard Fay-Herriot (no smoothing) and the naive variance smoothing model with df=#clusters - #strata. The naive variance smoothing model assumes that cluster means within a domain are distributed IID, so we will use the following variance models:

a. IID variance: 
    $$log(\sigma_{i}^{2(s)})\sim\mathcal{N}(\alpha,1/\tau)$$
b. Structured variance: 
  $$log(\sigma_i^{2(s)}) = \alpha + Z\gamma + v_i$$ 




